### PR TITLE
Convert site to jekyll for page generation

### PR DESCRIPTION
**Pull request by viv-codes**
Converting the generation of the site to jekyll would make changing elements like the footer, head, or navbar much easier, by only having to make changes on the template page, instead of on each individual page.

### CODE REVIEW

**Comment by 5HT2** [comment]
Thank you! I'll look over this today

**Comment by 5HT2** [comment]
Sorry for the incredibly late reply - I've been on vacation for a few weeks and was just able to get back to this.

Would you mind rebasing to the main branch and fixing the conflicts? I'll be free to look over it whenever (any hours outside of 09:00 to 15:00 PDT).

If not, I can try to create this from scratch if you don't mind linking docs / explaining what you're doing to make it compatible with jekyll. Thank you!

**Comment by viv-codes** [comment]
> Sorry for the incredibly late reply - I've been on vacation for a few weeks and was just able to get back to this.
> 
> Would you mind rebasing to the main branch and fixing the conflicts? I'll be free to look over it whenever (any hours outside of 09:00 to 15:00 PDT).
> 
> If not, I can try to create this from scratch if you don't mind linking docs / explaining what you're doing to make it compatible with jekyll. Thank you!

Will do! I'll work on that now

**Comment by viv-codes** [comment]
Hold on, I didn't mean to force push this.

**Comment by viv-codes** [comment]
Nvm I was confused sorry.

**Comment by viv-codes** [comment]
I'm going to make a new PR.

**Pull request closed without merging**
